language: node_js
node_js:
- '10'
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
script:
- cd frontend
- npm i
- ng lint
- ng build --prod --base-href /
env:
  global:
  - secure: Z+2eLezJBDwwYWHhZbGtqIVvrJGuWRmHO/lAqf9pSUqxMxcakUPsm7994/0P0QljT8aBJH7T96xdHgd8GkJ2dXD5O57iN5yimISdZIxUf650Qpp+hZhmTBnw+Inb0sp3mrnmCSD32fpM2ZPGHtgFeCrSWb49MLEBfrHVsmu7QpfxhflGxvrKqjIvRS0rEDkzLvt/vYynpbRB2+jAGK1fL6FJ+D3Q7dQl0wue0a7LU8s514DyaerxRNXDWHyIW3Dhx+7wPdbk2QPj6gk59uRWvTAAT4vZAhmTgV5NqN/csz2HUnXRhv38DJif2RHTnusYR1ADM6QUCq3ZRBT1rNHch8nzZmPj+DTh0dvZ2R7rUfpJ9BhwgvsIGbguoRRb/fht12RKCsPzVbte4TAp4UBR8/J58ELNJiZ/WF6lc8qh4A5O802U5CpBo9Nzt0IR4R4wuP9qvgZBeIVacqr/M3Kg26Cly2XfiqCMSs2CfTPHEWY0pdnx+4z+u9ySKH5ABnT0sOl3ql5lVoO/9/maMVkJ42dpWhB0gMLwDaGX+zoUhrKmNgBFRoFSPs+p93XngscrtPkMZ/wKaVRKk8ALlWaLyLOdNn2aXw5/2UyD+Ep5rMXaq70BoqWczLU2nhL6+igZJc8sT/Udi3/wCw9yIb1ouG5k42OxtLoTGdeVEpViyn4=
deploy:
  provider: pages
  repo: dhbwstudienarbeit2019/dhbwstudienarbeit2019.github.io
  target_branch: master
  fqdn: research.ieoca.org
  skip_cleanup: true
  local_dir: frontend/dist
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
