language: node_js
node_js:
- '10'
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
script:
- cd frontend
- npm i
- ng lint
- ng build --prod --base-href /
env:
  global:
    - secure: "Qq3EfKcEuEHx5QsSO8e8CLyiPeTOGO/agfjpCRmUxWQjkhExAL8m+NXOdWLp/L6mti/fuGJO1l95/BG3NItsxS73Y8KjCwGcdGoNIv4ysYDWTGTc+1axPLM76VYI2AfUeJXG5IsXGXBDC+ervOA7PV6xNUaH9SfSewfVpQ7rKitYX0ET5HkuuqPdj2u1rmgpxTtCZE/ENBW5lgCyWupS/CkJKOu3+TZvM7HWg5hiuMCezo7Pmh1Xp7bH6nWW/tO9Tz4B/nfycEZxidTtK++bsIwoFI7qWYx4V0xvuCGJ3eTmLK9vfblXB/4CaWwDnDpiKLqc+PjVqeKmqH1/fCBRfi5dvffvJHarnMT9UqaVcQvG+EFfnzxmQl/r09SGb3sI/emfzKZ63ztexMIeSNdcZaY8ogtgeisVYCZO0BJH18QjVK97r96olN+nqLlv3EA9cvMvf9fFGf927vTwY4QhA+oH7t7ckmSFbVPtpwcgdQCfdUI9Y+0ljJYz7J4GYznQca9kfSNkjTA0ScolgpPvif9syi6jranMxbZkWSx8AfRxyPngGEDiB2z4sGfT4VJukTrWqKJ7jVcj1ajmSIsMA/PpJu5+zxo2jv4wa18dQx8ef/6qqGF/jylXuUJYP9g/K+TI6qkNxqIMOG8wWfFwDMn7rGf0TsYKSX6MXYT2wGY="
deploy:
  provider: pages
  repo: dhbwstudienarbeit2019/dhbwstudienarbeit2019.github.io
  target_branch: master
  fqdn: research.ieoca.org
  skip_cleanup: true
  local_dir: frontend/dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master